<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishAot>true</PublishAot>
    <AssemblyName>vara</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Vara.Application\Vara.Application.csproj" />
    <ProjectReference Include="..\Vara.Infrastructure\Vara.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

</Project>
